name: Modrinth release
on: 
  push:
    tags:
      - '*'
jobs:
  zip:
    runs-on: ubuntu-latest
    if: ${{github.ref_type == 'tag'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
      - name: Get Branch
        id: get_branch
        run: |
          cd src
          tag=${{github.ref_name}}
          echo "tag=$tag" >> $GITHUB_ENV
          echo "name=tool-trim" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.name}}-${{env.tag}}
          path: src
      - name: Create datapack zip file
        run: zip -r ${{env.name}}-${{env.tag}}.zip . -x ".git/*" ".github/*" ".gitattributes" "supported_versions.txt" "add_on/*" "assets/*" "overlay_34/*" "overlay_43/*" "overlay_43_2/*" "overlay_44/*" "overlay_48_2/*" "overlay_65/*" "overlay_70/*"
        working-directory: src
      - name: Create resourcepack zip file
        run: zip -r ${{env.name}}-${{env.tag}}-resourcepack.zip . -x ".git/*" ".github/*" ".gitattributes" "supported_versions.txt" "add_on/*" "data/*" "overlay_48/*" "overlay_49/*" "overlay_58/*" "overlay_59/*" "overlay_63/*" "overlay_82/*" "overlay_89/*"
        working-directory: src
      - name: Create add-on datapack zip file
        run: zip -r ../${{env.name}}-${{env.tag}}-more-trim-materials-addon.zip . -x "assets/*" "overlay_34/*" "overlay_43/*" "overlay_44/*" "overlay_48_2/*" "overlay_65/*" "overlay_70/*"
        working-directory: src/add_on
      - name: Create add-on resourcepack zip file
        run: zip -r ../${{env.name}}-${{env.tag}}-more-trim-materials-addon-resourcepack.zip . -x "data/*" "overlay_48/*" "overlay_49/*" "overlay_58/*" "overlay_59/*" "overlay_63/*" "overlay_82/*" "overlay_89/*"
        working-directory: src/add_on
      - name: Read supported versions
        uses: andstor/file-reader-action@v1
        id: read_file
        with:
          path: src/supported_versions.txt
      - name: Upload to modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          project: aa6VCPUX
          name: Tool Trim ${{env.tag}}
          version: ${{env.tag}}
          files: '["src/${{env.name}}-${{env.tag}}.zip", "src/${{env.name}}-${{env.tag}}-resourcepack.zip", "src/${{env.name}}-${{env.tag}}-more-trim-materials-addon.zip", "src/${{env.name}}-${{env.tag}}-more-trim-materials-addon-resourcepack.zip"]'
          primary-file: ${{env.name}}-${{env.tag}}.zip
          file-types: '{"${{env.name}}-${{env.tag}}-more-trim-materials-addon-resourcepack.zip": "optional-resource-pack", "${{env.name}}-${{env.tag}}-resourcepack.zip": "required-resource-pack"}'
          game-versions: ${{steps.read_file.outputs.contents}}
          loaders: datapack